### ISSUE TITLE
Sample fails to run on Intel Windows Vulkan driver on HD530 iGPU..

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-LibrariesAndSDKs/OutOfOrderRasterization#1]
I know, I know that's an AMD Project, but since it runs on Nvidia GPUs just wanted
to mention it doesn't run on Intel Skylake iGPU Vulkan driver on Windows.. 
don't know using Intel Linux Vulkan driver which curiously is also named Anvil as your framework :-)
may test later..
on Windows it crashes on 
void App::draw_frame(void\* app_raw_ptr)
on line
    curr_frame_signal_semaphore_ptr = app_ptr->m_frame_signal_semaphores[app_ptr->m_n_last_semaphore_used].get();

fails on vector MSVC 2015 file with "vector subscript out of range":
    reference operator[](size_type _Pos)
        {   // subscript mutable sequence
 #if _ITERATOR_DEBUG_LEVEL == 2
        if (size() <= _Pos)
            {   // report error
            _DEBUG_ERROR("vector subscript out of range");
            _SCL_SECURE_OUT_OF_RANGE;
            }
hope it helps..

**Comment by oscarbg** [comment]
Went too fast too furious.. just testing in release mode works!
may still interesting to check why in debug mode doesn't Works!

**Comment by DominikWitczakAMD** [comment]
Thanks for reporting this issue. I think I know where that issue may be coming from. We will definitely address it in the next update.

**Comment by DominikWitczakAMD** [comment]
Should hopefully be addressed in the next Anvil release. Please re-open the ticket if that's not the case.
