### ISSUE TITLE
It's not allowed to transition swapchain images without first acquiring them

### ISSUE THREAD

**Issue by ratchetfreak** [GPUOpen-LibrariesAndSDKs/OutOfOrderRasterization#5]
https://github.com/GPUOpen-LibrariesAndSDKs/OutOfOrderRasterization/blob/master/Anvil/src/wrappers/swapchain.cpp#L325

Here you setup a resource transition for each image in the swapchain which you run during initialize without acquiring them. This is not allowed.

https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#_wsi_swapchain

> Use of a presentable image _must_ occur only after the image is returned by vkAcquireNextImageKHR, and before it is presented by vkQueuePresentKHR. **This includes transitioning the image layout and rendering commands.**

Instead you can set the `initialLayout` of the [renderpass attachment to VK_IMAGE_LAYOUT_UNDEFINED](https://github.com/GPUOpen-LibrariesAndSDKs/OutOfOrderRasterization/blob/bf3bdcc246e5aca4963f4fd34d9b7b9574b033cc/OOO_Rasterization/src/app.cpp#L666). Implying that you don't care about the existing data (which is made explicit by the load_op_clear).

For more info see http://stackoverflow.com/q/37524032/731620

**Comment by DominikWitczakAMD** [comment]
Thanks! Yeah, well spotted. Will patch this for the next Anvil release :-)

**Comment by ratchetfreak** [comment]
Whenever I see a vulkan example this is the first thing I look for, I have yet to see an example that didn't make this mistake (copied from the lunarg examples) initially.

**Comment by DominikWitczakAMD** [comment]
Should be fixed now.
